### ISSUE TITLE
container start fails with `network_mode: host`

### ISSUE THREAD

**Issue by robertgzr** [compose-spec/compose-ref#53]
**Description**

```
Creating container for service testsuite ... 2021/03/25 12:42:29 Error response from daemon: network-scoped alias is supported only for containers in user defined networks
```

```
services:
  test:
    image: alpine
	command:
		- sh
		- -c
		- ip link
    network_mode: host

```
